
site_name: Cerfs-volants
repo_url: https://github.com/gheleguen/KiteAerialPhotography
edit_uri: -/edit/main/docs/

nav:
    - Introduction: README.md
    - 1. Nacelles: 
      - 0.0.2 Nacelle éol à turbine : nacelle_ugrinsky_fr.md
      - 0.0.1 Nacelle éol à godets: nacelle_fr.md
    - 2. Cerfs-volants:
      - 2.1 Les cerfs-volants du commerce: Buy_KAP_fr.md
      - 2.2 Cerf-volant boite: made_box_kite_fr.md
      - 2.3 Eddy un cerf volant losange simple: made_eddy_fr.md
      - 2.4 Cerf-volant R8 DIY: made_R8_fr.md
    - tests: test_fr.md  
    - Liens connexes: liens_connexes_fr.md

     
    
        
theme:
    name: material
    palette:
      primary: green

plugins:
  - search

markdown_extensions:
    - smarty
    - sane_lists
    - admonition
    - toc:
        permalink: true
